name: cs_5446
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy=1.21.6
  - pandas=1.3.5
  - scipy=1.7.3
  - matplotlib=3.5.3
  - tqdm
  - psutil
  - ipykernel
  - ipython
  - jupyter
  - traitlets
  - tornado
  - tk
  - zlib
  - xz
  - zeromq
  - readline
  - sqlite
  - ncurses
  - zipp
  - typing-extensions
  - setuptools
  - wheel
  - ca-certificates
  - openssl
  - pip:
      - torch==1.13.1
      - stable-baselines3==1.7.0
      - pettingzoo==1.12.0
      - luxai-s2==2.1.9
      - gym==0.21.0
      - gymnasium==0.28.1
      - moviepy==1.0.3
      - pygame==2.6.1
      - cloudpickle==2.2.1
      - imageio==2.31.2
      - imageio-ffmpeg==0.5.1
      - matplotlib-inline==0.1.6
      - ipdb==0.13.13
      - decorator==4.4.2
      - requests==2.31.0
      - urllib3==2.0.7
      - protobuf==3.20.3
      - pyjwt==2.4.0
      - pyopenssl==23.0.0
      - charset-normalizer==3.4.1
      - markupsafe==2.1.1
      - werkzeug==2.2.2
      - tensorboard==2.10.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tqdm==4.67.1
      - termcolor==2.3.0
      - tomli==2.0.1
      - farama-notifications==0.0.4
      - vec-noise==1.1.4
      - jax-jumpy==1.0.0
